### ISSUE TITLE
Clip plane doesn't appear when you open issues from URL Link or Kanban Board

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2209] opened 2020-09-23 13:47 UTC
### Description
It looks like the clip plane does not appear in the view when you open issue from a URL link or Kanban Board. When you come out of the issue and open it again, the clip plane appears.

### Steps to replicate
- Open the [following Issue](https://www.3drepo.io/viewer/Bogdan_D/6dba85c6-58d5-4407-9c48-0a7ed744a1eb?issueId=85d74b70-fda2-11ea-90dd-3fa0fd8db936)
- Let the viewer load and camera position to change
- Come out of the Issue
- Open the same issue again (notice how the clip plane loads now)

### Pictures/ Gifs of the error
![Issue Clip Plane](https://user-images.githubusercontent.com/19904513/94021132-98063500-fdab-11ea-81a4-e822a0f7ecf0.gif)

**Comment by carmenfan** [comment] 2020-09-23 13:50
duplicate of  #2193

**Closed by carmenfan** 2020-09-23 13:50 UTC
