### ISSUE TITLE
Include Revit Element ID in object's metadata

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2515] opened 2021-03-03 11:27 UTC
### Description

Currently, Revit models imported to 3D Repo via Plugin or Direct upload do not include **element IDs** (similar to IFC GUIDs). This leads to real issues when performing model data checks via API using tools like Power BI. This is going to create a number of problems for projects wanting to utilise Revit Models & Power BI for data validation.

_For example, **Wall** is a single model element that is converted into **3 meshes** in 3D Repo. I can only use those **mesh IDs** to count totals which results in the wrong count. If there were Unique **Element IDs**, then I would use those and get the correct amount of walls in my project._ 

### Goals

- [ ] Include Revit Element ID in the BIM Data

### Related Resources
Model in 3D Repo : [`Architecture`](https://www.3drepo.io/viewer/Bogdan_D/a2b6bf80-7bfd-11eb-866f-9178b76b7801)
Revit File: [`Architecture Revit 2020`](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/3D%20Models/Element%20ID/School.rvt)

**Model in 3D Repo** (both via Plugin Upload & Direct Upload)
Family Name: **Basic Wall** Object count: **316 Objects**
![image](https://user-images.githubusercontent.com/19904513/109796505-24950900-7c10-11eb-9e57-67b568a098fa.png)

Model in Revit
Family Name: **Basic Wall** Object Count: **138 Instances**
![image](https://user-images.githubusercontent.com/19904513/109797236-198ea880-7c11-11eb-8e51-30fc40bb96c7.png)

**Revit Plugin** currently exports and includes Family Type ID in the BIM Card, but that's the same ID for multiple instances

![image](https://user-images.githubusercontent.com/19904513/109797522-8013c680-7c11-11eb-9d83-1415cf7e7318.png)

**Data in Power BI** is incorrect as the only number count parameter I can use is the **_id**
![image](https://user-images.githubusercontent.com/19904513/109798275-78a0ed00-7c12-11eb-9f8e-36ef6155c3c7.png)

**Comment by carmenfan** [comment] 2021-03-03 11:52
@BDavydov  this is a plugins/3drepobouncer issue. I can't transfer this issue into 2 different places, can you re-create them there?

closing this as nothing can be done for the web team.

**Closed by carmenfan** 2021-03-03 11:52 UTC

**Comment by BDavydov** [comment] 2021-03-03 12:05
@carmenfan Is this issue still relates to the **plugins/3drepobouncer** when it happens to Revit files uploaded directly on 3drepo.io?

**Comment by carmenfan** [comment] 2021-03-03 12:13
> @carmenfan Is this issue still relates to the **plugins/3drepobouncer** when it happens to Revit files uploaded directly on 3drepo.io?

if the issue is on direct uploads, it's an issue for 3drepobouncer

We extract metadata at the point of upload (unless it came from plugins, in which case the plugins do the extraction), 3drepo.io does not deal with uploads, 3drepobouncer does.
