### ISSUE TITLE
A 500 error is triggered when creating a ticket with bad payload

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3658] opened 2022-09-23 15:14 UTC
### Description
A 500 error is triggered if I send an extra comma in the body when ccreating a custom ticket

- This is happening in:  staging
- This requires a hotfix to production: no

### Steps to replicate
- Create a basic template with this body as payload
```
{
  "name": "Basic",
  "code": "BSC",
  "config": { },
  "deprecated": false,
  "properties": [],
  "modules": []
}
```
- get the template id
- Create a ticket for this template with this body  (there's an extra comma in the description field)
```
{
  "type": "aed6d220-3b2b-11ed-bbd7-8796720f88ae",
  "title": "First basic ticket!",
  "properties": {
    "Description": "This is the description of a basic ticket",
  },
  "modules": {}
}
```

### Current Behaviour
- It triggers a 500 error

### Expected Behaviour
-  Should triggers a 400 stating that is an invalid json.

**Comment by carmenfan** [comment] 2022-09-23 15:27
This is a duplicate of #2578

**Closed by carmenfan** 2022-09-23 15:27 UTC
Labels: bug, backend
