### ISSUE TITLE
Isolate model option leaves some parts of other model's visible

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2509] opened 2021-03-02 10:35 UTC
### Description

I have a large federation and when I select a model and click isolate in the toolbar, the rest of the models disappear. However, some models remain visible, not all just random parts.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [`Federation`](https://www.3drepo.io/viewer/Bogdan_D/0c2d99c8-a713-4974-b6fd-87a342de1b24)
- Open the model tree and select **Context** model
- In the toolbar click Isolate

### Current Behaviour
- Some model elements are not hidden

### Expected Behaviour
- Hide all of the models apart from the current selection

### Pictures/ Gifs of the error
[Issue GIF](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images/Model%20Isolation%20%28Federation%29.gif)

**Comment by Charence** [comment] 2021-03-24 10:25
This problem affects models, it is not caused by federations.

These two models have this problem:

- https://www.3drepo.io/viewer/Bogdan_D/762ef51d-d086-4d83-b7ad-edc50c86411a
- https://www.3drepo.io/viewer/Bogdan_D/43fb3374-e00e-4adb-8877-493dbf94ea1d

If you attempt to highlight the whole model by clicking the root node in the tree you can already see the problem as certain parts of the model will not appear highlighted in the viewer despite the tree indicating that they're highlighted. The affected parts of each model always remain the same; they are not random.

Still checking for the cause.

**Comment by mosment3DRepo** [comment] 2021-03-24 11:42
@Charence another Example:

[https://issue-2534.dev.3drepo.io/viewer/mosment3ddev/dbabd580-8bc2-11eb-82e6-5f80d4fd6019](https://issue-2534.dev.3drepo.io/viewer/mosment3ddev/dbabd580-8bc2-11eb-82e6-5f80d4fd6019)

### Steps to replicate
1. Open the groups tab
2. Select the group "Frame 1" (this contains the entire above ground aspect of the model, and contains the same elements as frame 1 of the sequence)
3. Isolate the elements in the group
4. Hide the selected elements
5. Notice everything hides correctly
6. 'Show All'
7. Select the group again
8. Hide selected objects
9. Notice that many of the elements do not get hidden correctly

### GIF of the error
[on dropbox](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images?preview=Issue+2509+io.gif)

**Comment by carmenfan** [comment] 2021-03-25 16:22
> This problem affects models, it is not caused by federations.
> 
> These two models have this problem:
> 
> * https://www.3drepo.io/viewer/Bogdan_D/762ef51d-d086-4d83-b7ad-edc50c86411a
> * https://www.3drepo.io/viewer/Bogdan_D/43fb3374-e00e-4adb-8877-493dbf94ea1d
> 
> If you attempt to highlight the whole model by clicking the root node in the tree you can already see the problem as certain parts of the model will not appear highlighted in the viewer despite the tree indicating that they're highlighted. The affected parts of each model always remain the same; they are not random.
> 
> Still checking for the cause.

This was caused by the logic for splitting the highlight request into chunks. We're using slice to slice the array into chunks, but the end index is always set to `chunkSize`, so it only ever works on the first and last request... 😆 

This is now fixed on this branch, checking the other scenarios to see if it's to do with the same thing.

**Closed** 2021-04-22 14:25 UTC
Labels: In Staging, bug
