### ISSUE TITLE
Frontend not getting messages about new containers when containers created using api key

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4038] opened 2023-03-02 11:51 UTC
### Description

If we use an API key to create new containers whilst watching the project from a browser, the front end doesn't get any chat messages about the existence of a new container. If you use the UI to create new containers, then it's sometimes possible to see the new container created on another browsers view of the project but also not 100% reliable.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- navigate to drop folder `~\Dropbox (3D Repo)\3D Repo Team Folder\Product\Integrations\Powershell`
- run `.\BatchUpload.ps1 -globalEndpoint https://3drepo.lan/api/ -project <project> -recursive -pathToScan "C:\temp\models\" -apiKey <apiKey> -teamspace <teamspace>`
> **note** replace `<project>` with an existing project
`<apiKey>` with the api you can get from the editProfileModal
`<teamspace>` with the teamspace containing the project

### Current Behaviour
- the frontend does not show the new containers until the page is refreshed

### Expected Behaviour
- the frontend should show the new containers straight away (no need to refresh)

### Notes
Check whether the problem is in the frontend or the backend not sending the chat notification (most likely the case)

**Comment by carmenfan** [comment] 2023-03-16 10:43
this might be fixed by #4034 (depends if it only happens if you had to log in to start your session)

Maybe try it once that's merged in

**Comment by Amantini1997** [comment] 2023-03-17 12:11
> this might be fixed by #4034 (depends if it only happens if you had to log in to start your session)
> 
> Maybe try it once that's merged in

#4034 has been merged, so I set my local to staging and tried it again. The result is the backend crashes and restarts a couple of times and the frontend does not get the chat event
![image](https://user-images.githubusercontent.com/43547703/225899813-b9ec18db-735f-45ea-ac2e-98f59e4530cf.png)

https://user-images.githubusercontent.com/43547703/225900093-42c7c222-daad-499f-93f4-2be526930bd2.mp4



<details style="background: lightblue;">
<summary>Backend logs</summary>
<code>2023-03-17T12:01:26.177Z [info] [NET]   200     OK      7       4127    localuser1      GET     /api/localuser1/projects?key=8b935531d57c77c625b92610f5998a41
2023-03-17T12:01:26.195Z [info] [NET]   200     OK      6       4127    localuser1      GET     /api/localuser1/projects?key=8b935531d57c77c625b92610f5998a41
2023-03-17T12:01:26.216Z [info] [NET]   200     OK      8       515     localuser1      POST    /api//localuser1/model?key=8b935531d57c77c625b92610f5998a41
2023-03-17T12:01:26.220Z [debug] [CHAT]         [notifications::localuser1][NEW EVENT]: localuser1::modelCreated      {"account":"localuser1","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","name":"LegoRoundTree (5)","permissions":["change_model_settings","upload_files","create_issue","comment_issue","view_issue","view_model","download_model","edit_federation","delete_federation","delete_model","manage_model_permission"],"projectName":"w"}
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
2023-03-17T12:01:26.323Z [info] [MODPRO]        [Received][71a439f0-c4bb-11ed-a4e6-57a771f4abb4] {"status":"processing","database":"localuser1","project":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4"}
2023-03-17T12:01:26.323Z [debug] [EVENT]        [QUEUED_TASK_UPDATE] : {"teamspace":"localuser1","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","corId":"71a439f0-c4bb-11ed-a4e6-57a771f4abb4","status":"processing"}
2023-03-17T12:01:26.324Z [debug] [EVENT]        [QUEUED_TASK_UPDATE] : {"teamspace":"localuser1","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","corId":"71a439f0-c4bb-11ed-a4e6-57a771f4abb4","status":"queued"}
2023-03-17T12:01:26.327Z [debug] [EVENT]        [MODEL_SETTINGS_UPDATE] : {"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","data":{"status":"processing"},"isFederation":false}
2023-03-17T12:01:26.330Z [info] [NET]   200     OK      90      21      localuser1      POST    /api//localuser1/7198ef50-c4bb-11ed-a4e6-57a771f4abb4/upload?key=8b935531d57c77c625b92610f5998a41
2023-03-17T12:01:26.330Z [debug] [EVENT]        [MODEL_SETTINGS_UPDATE] : {"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","data":{"status":"queued"},"isFederation":false}
2023-03-17T12:01:26.339Z [debug] [CHAT]         [localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::7198ef50-c4bb-11ed-a4e6-57a771f4abb4][NEW EVENT]: containerSettingsUpdate  {"data":{"status":"processing"},"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4"}
2023-03-17T12:01:26.339Z [debug] [CHAT]         [localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::7198ef50-c4bb-11ed-a4e6-57a771f4abb4][NEW EVENT]: containerSettingsUpdate  {"data":{"status":"queued"},"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4"}
2023-03-17T12:01:26.339Z [debug] [CHAT]         [localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::7198ef50-c4bb-11ed-a4e6-57a771f4abb4][NEW EVENT]: localuser1::7198ef50-c4bb-11ed-a4e6-57a771f4abb4::modelStatusChanged   {"status":"processing"}
2023-03-17T12:01:26.340Z [debug] [CHAT]         [localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::7198ef50-c4bb-11ed-a4e6-57a771f4abb4][NEW EVENT]: localuser1::7198ef50-c4bb-11ed-a4e6-57a771f4abb4::modelStatusChanged   {"status":"queued"}
[nodemon] starting `node ../3drepo.io/backend/src/v4/3drepo.js`
2023-03-17T12:01:27.073Z [info] [APP]   Setting umask: 2
2023-03-17T12:01:27.079Z [info] [APP]   Loading api on 3drepo.lan:443
2023-03-17T12:01:27.566Z [info] [AMQP]  Connecting to amqp://nodeWorker:nodeWorker@localhost:5672...
2023-03-17T12:01:28.022Z [info] [APP]   Loading frontend on 3drepo.lan:443
2023-03-17T12:01:28.471Z [info] [APP]   Loading chat on chat.3drepo.lan:3000
2023-03-17T12:01:28.481Z [info] [APP]   Starting routing HTTP for 3drepo.lan service on port 8080
2023-03-17T12:01:28.481Z [info] [APP]   Starting server on 0.0.0.0 port 3000
2023-03-17T12:01:28.481Z [info] [APP]   Starting server on 0.0.0.0 port 443
2023-03-17T12:01:28.556Z [debug] [CHAT]         [aAaBDDpVKWaPM1swAAAB][localuser1][Xg9HrDo62w7vllxTbTWdLvwqw5wYERKc]  connected
2023-03-17T12:01:28.575Z [debug] [CHAT]         [aAaBDDpVKWaPM1swAAAB][localuser1][Xg9HrDo62w7vllxTbTWdLvwqw5wYERKc]  has joined localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48
2023-03-17T12:01:28.580Z [info] [MODPRO]        [Received][71a439f0-c4bb-11ed-a4e6-57a771f4abb4] {"status":"Queued for Unity","database":"localuser1","project":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4"}
2023-03-17T12:01:28.580Z [debug] [EVENT]        [QUEUED_TASK_UPDATE] : {"teamspace":"localuser1","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","corId":"71a439f0-c4bb-11ed-a4e6-57a771f4abb4","status":"Queued for Unity"}
2023-03-17T12:01:28.581Z [info] [MODPRO]        [Received][71a439f0-c4bb-11ed-a4e6-57a771f4abb4] {"status":"Generating Bundles","database":"localuser1","project":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4"}
2023-03-17T12:01:28.581Z [debug] [EVENT]        [QUEUED_TASK_UPDATE] : {"teamspace":"localuser1","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","corId":"71a439f0-c4bb-11ed-a4e6-57a771f4abb4","status":"Generating Bundles"}
2023-03-17T12:01:28.583Z [debug] [CHAT]         [aAaBDDpVKWaPM1swAAAB][localuser1][Xg9HrDo62w7vllxTbTWdLvwqw5wYERKc]  has joined localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::a256d0b0-bf54-11ed-8314-d955229de920
2023-03-17T12:01:28.585Z [debug] [CHAT]         [aAaBDDpVKWaPM1swAAAB][localuser1][Xg9HrDo62w7vllxTbTWdLvwqw5wYERKc]  has joined localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::c4bbe640-bf54-11ed-a31d-33c5455f40ff
2023-03-17T12:01:28.591Z [debug] [CHAT]         [aAaBDDpVKWaPM1swAAAB][localuser1][Xg9HrDo62w7vllxTbTWdLvwqw5wYERKc]  has joined localuser1::765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48::e28be230-c358-11ed-81bc-91c63434d015
2023-03-17T12:01:28.592Z [debug] [EVENT]        [MODEL_SETTINGS_UPDATE] : {"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","data":{"status":"Queued for Unity"},"isFederation":false}
2023-03-17T12:01:28.595Z [debug] [EVENT]        [MODEL_SETTINGS_UPDATE] : {"teamspace":"localuser1","project":"765c4c60-bf2c-11ed-a8c2-f1e0aa55ab48","model":"7198ef50-c4bb-11ed-a4e6-57a771f4abb4","data":{"status":"Generating Bundles"},"isFederation":false}
</code>
</details>

**Comment by carmenfan** [comment] 2023-03-22 12:03
@keifgwinn  throwing this back to you. @Amantini1997 is saying this is reproducible with just one model in the folder. To make this easier to test can you extrapolate the endpoints you are calling with the parameters so we have a clear reproducible steps to reproducing this without the need to figure out how to run an external script. I can't manually reproduce this outside of the script. And the script won't play ball with me (even if it does, it'd be good if we don't have to cherry pick out the problem from a script so we can reproduce this easily as that would be the first thing we'd have to do): 
![image](https://user-images.githubusercontent.com/11945337/226899156-312a8e7e-5988-4602-bce2-2f2b96c8c25e.png)


It is also using v4 endpoints - probably good to upgrade it to use v5 ones

**Comment by keifgwinn** [comment] 2023-03-22 12:10
this script requires powershell 7 which is why you're getting those errors, work ceased on it when I was told not to bother due to v5.

**Comment by carmenfan** [comment] 2023-03-22 12:20
@keifgwinn I need instructions that are reproducible without an external script. If the script can crash the backend with just 1 model in the folder there should be one or few endpoints you're calling there with parameters that we can utilise in postman or something to re-produce the situation.

Without that I'm reluctant to move forward, if this is a deprecated script then maybe we should just close the issue.

**Comment by keifgwinn** [comment] 2023-03-22 14:13
the issue was raised specifically to the fact that new containers aren't appearing when created, the crash also observed whilst testing.

https://www.dropbox.com/s/mkwtl544dw5ide1/issue-4038.zip?dl=0 contains debug output from the script showning the calls made to upload files, the end points, and the post minus the actual file data, plus a har recording of the ui watching it, IO's logs, and a video of the whole thing going down.

**Comment by carmenfan** [comment] 2023-03-22 14:23
@keifgwinn still the same words - I need reproducible instructions on just endpoint calls and the parameters supplied.

Yes I can take all that info and figure it out - but we're very stretched on backend dev man power and since you wrote the script you'd be way more familiar with it anyway

Moving this back to `awaiting triage` as it doesn't seem to affect normal 3drepo usage and it's using v4 endpoints, until we have a better understanding what's at fault here it's not deemed release critical.

**Comment by carmenfan** [comment] 2023-03-22 15:27
Ok this is a won't fix.

New container event is a v5 feature, using a v4 endpoint it doesn't trigger the v5 event. This is too niche to worth fixing.

You can easily fix this by just creating the container using v5 endpoint.

**Closed by carmenfan** 2023-03-22 15:27 UTC
Labels: bug, backend

**Comment by keifgwinn** [comment] 2023-03-22 18:05
The most popular integration is model upload. And so this affects every existing integration until they update to v5 endpoints. --KeifOn 22 Mar 2023, at 15:27, Carmen Fan ***@***.***> wrote:﻿
Ok this is a won't fix.
New container event is a v5 feature, using a v4 endpoint it doesn't trigger the v5 event. This is too niche to worth fixing.
You can easily fix this by just creating the container using v5 endpoint.

**Comment by carmenfan** [comment] 2023-03-22 18:15
> The most popular integration is model upload. And so this affects every existing integration until they update to v5 endpoints. --KeifOn 22 Mar 2023, at 15:27, Carmen Fan ***@***.***> wrote:﻿ Ok this is a won't fix. New container event is a v5 feature, using a v4 endpoint it doesn't trigger the v5 event. This is too niche to worth fixing. You can easily fix this by just creating the container using v5 endpoint. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Then perhaps it gives incentives for them to use v5 endpoints then.
