### ISSUE TITLE
Meshes of an edited ticket group are not being unhighlighted with the toolbar 'Clear Overrides' button

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4710] opened 2024-01-19 17:17 UTC
### Description
After editing a group the 'Clear overrides' toolbar option does not work on the meshes highlighted by the edited group.
Therefore it is possible to have meshes highlighted and not have the toolbar options to clear overrides by editing a ticket's groups.

This only happens on custom tickets groups, not v4 groups.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open a ticket that has a view.
- Create a group with objects. (Can be smart or manual, but manual is easier)
- Click edit group
- Cancel the edit
![image](https://github.com/3drepo/3drepo.io/assets/62481250/112e258a-2a9d-4695-94de-bbe3340e2e73)
- Click 'Clear overrides in the toolbar
- The meshes of the edited group are not cleared and the toolbar option to clear overrides disappears. The group is 'unticked' in the group list
![image](https://github.com/3drepo/3drepo.io/assets/62481250/bd29dc06-c31a-488a-b72d-cb4a7bf6ad95)

### Current Behaviour
- The meshes of edited groups are not unhighlighted when clicking 'clear overrides'

### Expected Behaviour
- All highlighted meshes are cleared

**Comment by carmenfan** [comment] 2024-01-22 11:57
Pretty sure we've been through this previously.

Highlight and colour override are 2 different concepts. If you're highlighting something you have the object selected - you click away, the highlight disappears. It's a bit like in word, highlighting a bunch of text but selecting it with your mouse so it's rendered in a different colour with background

Colour override is imposing a colour on an object. if you click away, it stays, it is not highlighted (i..e if it's obscured by something else, you won't see the object) - think actually imposing a colour/colour background on text.

Unless i've mistaken, this is not a bug, so closing. Reopen with more details if I understood this incorrectly!

**Closed by carmenfan** 2024-01-22 11:57 UTC
Labels: bug, frontend

**Comment by The-Daniel** [comment] 2024-01-23 12:39
> Pretty sure we've been through this previously.
> 
> Highlight and colour override are 2 different concepts. If you're highlighting something you have the object selected - you click away, the highlight disappears. It's a bit like in word, highlighting a bunch of text but selecting it with your mouse so it's rendered in a different colour with background
> 
> Colour override is imposing a colour on an object. if you click away, it stays, it is not highlighted (i..e if it's obscured by something else, you won't see the object) - think actually imposing a colour/colour background on text.
> 
> Unless i've mistaken, this is not a bug, so closing. Reopen with more details if I understood this incorrectly!

Sorry, I got some of the terms mixed up because it seems like a weird combination of colour override and highlight. I do still think this is a bug. It seems to create a coloured highlight which can't be cleared in the toolbar. It is not a colour override since clicking the background will remove it, however it doesn't have the typical mesh selection colour. To me it seems wrong to have a highlight that acts differently by not showing the same toolbar options and therefore cannot be removed with the toolbar other than by going to the home view. 

There is also this related bug
- Edit a group and then cancel the edit.
- Click 'Isolate' followed by 'Hide'. This hide's all the objects.
![image](https://github.com/3drepo/3drepo.io/assets/62481250/35df3725-2b7b-4176-824f-ada45a695999)
- Now click 'Clear overrides'
![image](https://github.com/3drepo/3drepo.io/assets/62481250/d372b4ae-997e-4b4e-9564-1b4e5d11ed0c)
- The 'coloured highlight' now returns. (Clicking the background will clear the highlight and show the object which the user just hid)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/b9a7cbbe-399c-4100-8788-d95cba578d90)
