### ISSUE TITLE
I am a collaborator & I can not update Risk Pin, Image & Viewpoint

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2194] opened 2020-09-16 13:34 UTC
### Description
Currently as a collaborator I can open a risk card and edit any of the fields. However the buttons for _Edit Pin, Edit Image & Update Viewpoint_ are greyed out. Since we have allowed the collaborators to update risk information, this should also be updatable. Some of our users need to issue information at the end of the week, so it's crucial for them to update the risk information.

### Steps to replicate
- Open any model in 3D Repo that contains Risks
- Open any risk as a project collaborator
- Try and edit the Pin/Image/Viewpoint
- Only fields of information work

### Pictures/ Gifs of the error
![SafetiBase Buttons Bug](https://user-images.githubusercontent.com/19904513/93344454-a0012a80-f829-11ea-8ce7-9c73210d84bf.gif)

**Comment by carmenfan** [comment] 2020-09-16 13:43
@3drepo/product-team Just recording down what was discussed on MS Teams:

This is working as intended, this was the proposed and accepted change.

The main reason for those fields to be admin only is to to be consistent with issues, so we decided only risk specific fields can be changed by commenter+.

There's also the argument that if the risk has to be changed so drastically then they should set this one as void and clone it with fixed values. With the new numbering reference feature they could still point users to the old risk where apprioriate.

**Comment by carmenfan** [comment] 2020-09-17 11:32
Closing this as there's no bug here. 

Reopen again with instructions if you want the behaviour changed

**Closed by carmenfan** 2020-09-17 11:32 UTC
Labels: invalid
