### ISSUE TITLE
Having 2 viewers open at the same time does not render the right content at first

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4050] opened 2023-03-07 12:26 UTC
### Description

Having 2 tab opened in the same browser that use different models does not work as intended.
Updating the viewpoint of either, changes what can be seen in the other (the video explains that better than I do with words).

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open a model in a tab
- Open another model in another tab (same browser)

### Current Behaviour
- Updating the viewpoint of the first model, updates the viewpoint of the other one as well

### Expected Behaviour
- Updating the viewpoint of the first model should not affect the other one

### Pictures/ Gifs of the error

https://user-images.githubusercontent.com/43547703/223420925-2ba74fda-91b9-435d-9176-410f353211f2.mp4

**Comment by carmenfan** [comment] 2023-03-07 17:43
@anorrie  also seen this situation before. I just tried it and can't reproduce....


does this always happen for you no matter which model?

**Comment by carmenfan** [comment] 2023-08-01 17:13
closing as this I have never managed to reproduce.

Reopen if there is a reliable set of instructions that can be reproduced by more than one person

**Closed by carmenfan** 2023-08-01 17:13 UTC
Labels: bug, viewer
