### ISSUE TITLE
When a model finished processing the timestamp is updated, but the revision count is not updated.

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2415] opened 2021-01-21 16:52 UTC
### Description

When a model finished processing the timestamp is updated, but the revision count is not updated.

- This is happening in: both
- This requires a hotfix to production: no
- 
### Steps to replicate
- have multiple models visible on the screen
- upload models and wait for the results
- view the revision counter

### Current Behaviour
- The current revision count doesn't update at the same time as the last revision date
- if you refresh the page the correct revision count is displayed

### Expected Behaviour
- Revision count should be correctly updated without a forced refresh

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/23369849/105381417-e404a180-5c06-11eb-93e6-996d383a05c0.png)

**Comment by keifgwinn** [comment] 2021-02-09 12:56
Additionally I've noticed that newly created federations aren't available until a page refresh

**Comment by keifgwinn** [comment] 2021-05-25 09:49
This is still present in 4.16.0

**Comment by carmenfan** [comment] 2021-05-25 10:00
@keifgwinn that's expected, the issue isn't marked as resolved! :P

**Comment by carmenfan** [comment] 2022-09-30 16:23
closing as N/A after v5

**Closed by carmenfan** 2022-09-30 16:23 UTC
Labels: bug, frontend
