### ISSUE TITLE
TypeErrors - unhandled exceptions

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3960] opened 2023-02-13 11:36 UTC
### Description

Reviewing the system logs after a few days operation, small number of unhandled exceptions are apparent.

- This is happening in: prod
- This requires a hotfix to production: (probably) yes 

### Steps to replicate
- Review the documents on dropbox for the details
- Details include customer information required for debug, so not placing in public domain.

### Current Behaviour
- Unhandled exceptions and errors thrown

### Expected Behaviour
- Gracefully handled / no errors

### Pictures/ Gifs of the error

- [x] #3963 (wont' fix for this issue)
- [x] customer2
- [ ] customer3
- [ ] https://github.com/3drepo/3drepo.io/issues/3964

https://www.dropbox.com/s/205nvi39hogvwra/customer1.txt?dl=0
https://www.dropbox.com/s/smony9la7s3w7h6/customer2.txt?dl=0
https://www.dropbox.com/s/6ziq189vahjo8xz/customer3.txt?dl=0
https://www.dropbox.com/s/wxetr9weyh8bmd0/customer4.txt?dl=0

**Comment by carmenfan** [comment] 2023-02-13 12:08
#### customer1 
Before v5 upgrade, ignoring

#### customer2
dodgy data (There are job entries without users array, which is not expected). I have updated all the jobs in that teamspace so the query should now work.

I also did a find() on all production teamspaces and found that the problem only occurs on that particular teamspace - so no other action is necessary. As it is an isolated incident I'm not going to write a script for it.

If we see it on another deployment, this is what we need to run:
````
db.getCollection('jobs').updateMany({users: {$exists: false}}, {$set: {users: []}})
````

**Comment by keifgwinn** [comment] 2023-02-13 12:24
I've updated customer1 with a post upgrade alternative error

**Comment by carmenfan** [comment] 2023-02-13 13:05
#### Customer 1 (new)
The endpoint is tipping over the server due to running out of memory.

The situation is that the user is trying to access the sequence list of a federation, which consist of 108 sub models. I have no idea how many of them have sequences but I'd imagine quite a few and perhaps with quite a few frames each.

so it's pulling sequence data from 108 different models, scrubbing them clean for return hence running out of memory. We don't anticipate data to be this big so to support it properly we'd have to rethink/rewrite the situation.

I don't believe this is caused by v5. so creating a separate issue for @mosment3DRepo  to triage

**Comment by carmenfan** [comment] 2023-02-13 15:07
closing as any unsolved issues are now separate issue. With the exception of customer 3 which cannot be reproduced

**Closed by carmenfan** 2023-02-13 15:07 UTC
Labels: bug, Triage: Awaiting
