### ISSUE TITLE
Not saving any changes when editing fields in a custom ticket 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4392] opened 2023-08-08 16:42 UTC
### Description
No longer saving any information when editing any of the fields in a custom ticket 

- This is happening in: production

### Steps to replicate
- Open this model: [link](https://www.3drepo.io/v5/viewer/Faisal_Ramady/0025aeb0-3605-11ee-abb2-8da26270611f/0b9ed8c0-3605-11ee-9360-098436b61ce2)
- Create a test ticket and try to edit any of the fields 

### Current Behaviour
- Not able to edit or create any new custom tickets

### Expected Behaviour
- Be able to create and edit custom tickets

**Comment by carmenfan** [comment] 2023-08-09 09:34
@Ramadyfm I can't reproduce, I can create a ticket for both templates available as long as I filled in the required fields.
![image](https://github.com/3drepo/3drepo.io/assets/11945337/1f25b2c0-12b1-45d9-a016-c9458a02f842)

there are 3 requiremed fields hidden in a module - did you fill them in? 
![image](https://github.com/3drepo/3drepo.io/assets/11945337/d6357708-7d2c-4cee-bbd0-c5db01c31219)

**Comment by carmenfan** [comment] 2023-08-10 10:43
closing until there's better instructions.

**Closed by carmenfan** 2023-08-10 10:43 UTC
Labels: bug
