### ISSUE TITLE
Surface Area measurement throws an error code and crashes the web page

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2566] opened 2021-04-15 15:41 UTC
### Description

When I activate the surface area measurement feature and click on the mesh highlighted in the screenshot, I get an error message which leads to a page refresh and eventually crashes. 

- This is happening in: prod/
- This requires a hotfix to production: no

### Steps to replicate
- Open this Model: [`Facade`](https://www.3drepo.io/viewer/Demo_3D_Repo/11da8980-6e82-11ea-a9b4-253aa7f93e55?issueId=dbe06670-9dff-11eb-b396-8d5a8b231884)
- Open the Measurements card
- Activate surface area measurement feature
- Click on the mesh with the Issue pin

### Current Behaviour
- Get an error message

### Expected Behaviour
- Show me a surface area measurement

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/19904513/114897635-57364200-9e09-11eb-91fc-144a14d39598.png)

![image](https://user-images.githubusercontent.com/19904513/114897566-471e6280-9e09-11eb-87d6-f11448751371.png)

**Comment by carmenfan** [comment] 2021-04-15 16:57
@BDavydov Just a quite sanity check - is the units right on this model? (e.g. we don't have something like a mm measurement with a m label right?)

**Comment by sebjf** [comment] 2021-04-16 10:23
Hi @BDavydov, @carmenfan, it seems the build on production (v4.13.5?) was created with the [WebAssembly Arithmetic Exceptions set to Throw instead of Ignore](https://github.com/3drepo/3drepounity/blob/272f0c08784c9293fbdf03978f25d940e37738b5/AssetBundleViewer/ProjectSettings/ProjectSettings.asset#L583).

This is a [known bug](https://github.com/3drepo/3drepounity/issues/342) (that is arguably not a bug) and has a workaround (that is arguably the fix), that is on staging. 
My recollection is that it's been on staging for a while so it may have been a merge issue, but the production version may also be older than I recall!

**Comment by carmenfan** [comment] 2021-04-16 10:29
@sebjf  it might've been accidentally turned on when I changed the exception settings 😆 

In that case I guess we can close this (and the unity issue).

**Closed by carmenfan** 2021-04-16 10:29 UTC

**Comment by BDavydov** [comment] 2021-04-16 11:14
@carmenfan Currently, our measurements show up as m regardless of whether the model units are in m or mm. Of course you can toggle the measurement units to come up as mm if you wish

**Comment by carmenfan** [comment] 2021-04-16 11:37
@BDavydov that was by design. it default sot show in m unless it's ft.

The values should be correct though? (i.e. a mm model it would scale it accordingly, instead of showing you the mm value with a m label.)

**Comment by BDavydov** [comment] 2021-04-16 16:16
@carmenfan Yeah, mm scale fine for m values!
