### ISSUE TITLE
Log user out when session closes

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#341] opened 2017-03-15 16:45 UTC

**Comment by carmenfan** [comment] 2017-09-29 11:33
Is this done? It's moved to done but there's no reference commit (nor tagged against anything

**Comment by JamesMilnerUK** [comment] 2017-09-29 14:11
this is a duplicate of #383 essentially. We need to work out the session timer and then send a interval request for that time to check the login API and logout if necessary.

**Comment by JamesMilnerUK** [comment] 2017-10-04 11:03
Closing in favour of #383

**Closed by JamesMilnerUK** 2017-10-04 11:03 UTC
