### ISSUE TITLE
Coordinates do not display correctly on high DPI displays

### ISSUE THREAD

**Issue by har00n-haider** [3drepo/3drepo.io#2436] opened 2021-01-29 10:37 UTC
### Description
The coordinates display does not play nice with high DPI screens (really puny numbers, see screenshot)

- This is happening in: both

### Steps to replicate
- Click the target icon to show coordinates, then move the window on to a high DPI monitor

### Expected Behaviour
- Text should be the same size as on normal DPI settings
- 
### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/72197495/106264682-e3c76000-621d-11eb-8337-fd9b2ecc301a.png)

**Comment by carmenfan** [comment] 2021-01-29 10:39
this is a duplicate of https://github.com/3drepo/3drepounity/issues/300

**Closed by carmenfan** 2021-01-29 10:39 UTC
Labels: bug
