### ISSUE TITLE
Object selection in tree doesn't show/update metedata when Meta tool is active

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#907] opened 2018-04-17 15:19 UTC
1. Activate Meta tool
2. Select a object in tree
3. Metadata card should pop up or update card if previously opened

![image](https://user-images.githubusercontent.com/760452/38879309-eb5011ae-425a-11e8-9b81-705df07b8583.png)

**Comment by JamesMilnerUK** [comment] 2018-04-26 09:29
I can't reproduce this in staging any more

**Comment by carmenfan** [comment] 2018-04-26 13:53
closing this then.

**Closed by carmenfan** 2018-04-26 13:53 UTC
Labels: bug, low
