### ISSUE TITLE
Creation of tree folders to group together and find disciplines 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4331] opened 2023-07-13 07:45 UTC
### Description
Ability to create tree main folders in the 3drepo.io viewer so that clients can organise their model disciplines and find objects more easily.

### Goals
Goal is accomplished if the client can drag their specific models into the created folders and expand/collapse them.

**Comment by carmenfan** [comment] 2023-07-13 09:18
duplicate of https://github.com/3drepo/3D-Repo-Product-Team/issues/304

**Closed by carmenfan** 2023-07-13 09:18 UTC
Labels: feature
