### ISSUE TITLE
Remove vm.modelSettings and watchers, replace with ViewerService promise

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#572] opened 2017-11-06 14:51 UTC
Watching/EventService for vm.modelSettings has caused problems in previous versions. We can hopefully end further problems once and for all by using promises.

**Comment by carmenfan** [comment] 2017-11-06 15:12
Moving this to 2.5, let's keep 2.3 as small as it was intended to be

**Comment by carmenfan** [comment] 2018-09-18 15:30
I think we already do this

**Closed by carmenfan** 2018-09-18 15:30 UTC
Labels: Tech Debt
