### ISSUE TITLE
Favourite models are missing since new version release 4.14

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2493] opened 2021-02-24 13:20 UTC
### Description

I have logged in to 3drepo.io and lost all of my favourite models. On the other hand, if I add new favourite models, they appear in the list.

- This is happening in: prod
- This requires a hotfix to production: yes/no

### Steps to replicate
- Log in to 3drepo.io
- Head over to your Favourites tab
- Nothing to display

### Current Behaviour
- No favourites

### Expected Behaviour
- Contain favourites from before

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/109006398-f27d2780-76a2-11eb-88e8-56a5cdd63d14.png)

**Comment by carmenfan** [comment] 2021-02-24 14:55
@BDavydov  

just adding some context here.

This is not easily reproducible. The favourites logic seems to be intact. I can see my list of favourites fine, and removing/adding models doesn't seems to cause me to lose my existing favourited models.

For some reason your favourites are getting wiped out, and until we can figure what what is the action that caused your favourites to be removed, we can't really fix the bug.

**Comment by BDavydov** [comment] 2021-02-26 12:20
@carmenfan Okay, it seems odd. Any model that I make a favourite from now on, works fine. It's just a list of about 10-15 models I had before the 4.14 release that have disappeared. Oh well, what's gone is gone.

**Comment by carmenfan** [comment] 2021-03-02 12:17
closing this for now since there's nothing we can do here. Feel free to reopen it if you figured out what is clearing your favourites!

**Closed by carmenfan** 2021-03-02 12:17 UTC
Labels: bug
