### ISSUE TITLE
Risk/Issue shapes are still visible when you come out of them

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2758] opened 2021-09-01 07:52 UTC
### Description

When I create an Issue or a SafetiBase risk, there is an option to add shapes. Unfortunately, after I save an Issue or a Risk with shapes and come out of them, the shapes are still visible. There is no way to make them disappear.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Log in to 3D Repo and open any model
- Create an Issue/Risk
- Add som shapes
- Exit the newly created Risk or Issue
- Shapes are still around

### Current Behaviour
- Shapes remain in place

### Expected Behaviour
- Should disappear when I come out of an Issue/Risk (no longer reviewing those)

### Pictures/ Gifs of the error
![Shapes bug](https://user-images.githubusercontent.com/19904513/131633575-8b7acc49-3b2e-4bfe-8e3d-f45a19abfc4e.gif)

**Comment by mosment3DRepo** [comment] 2021-09-10 19:09
@BDavydov in this example do you have the 4D sequence loaded? It may be that it's set to a date where the pin and shape is relevant

**Comment by BDavydov** [comment] 2021-09-14 10:35
@mosment3DRepo You're correct, it's linked to a Sequence. So I gather that Issue/SafetiBase shapes appear in the model just as pin icons? 
![SafetiBase Shapes](https://user-images.githubusercontent.com/19904513/133242735-e5ef17d6-0d72-4887-9999-057dbdd9fad3.gif)

**Comment by carmenfan** [comment] 2021-09-14 10:37
@BDavydov in sequences yes. it appears and disappears like pins. Outside of sequences it only appears when the issue is selected.

**Comment by BDavydov** [comment] 2021-09-14 10:40
@carmenfan In that case, this may no longer be an issue/bug, but my personal learning curve of 3D Repo. The shape seems to disappear when I come out of a risk and don't have an active sequence. Apologies.

**Comment by carmenfan** [comment] 2021-09-14 10:50
👍  

closing!

**Closed by carmenfan** 2021-09-14 10:50 UTC
Labels: bug
