### ISSUE TITLE
v5 License viewing with multiple licenses 

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3718] opened 2022-10-31 11:41 UTC
### Description

An internal testing teamspaces license expired, so I used the management script to change the date on the license. It added it as a different type of license. when viewed in v5 it's not picking up the new active license as the account now has two licenses, one expired "enterprise" license and one active "internal" license,

<img width="431" alt="image" src="https://user-images.githubusercontent.com/23369849/198999546-f4cfc30d-7503-450f-86f2-7ab190cd71c9.png">

- This is happening in: staging 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- License was set to be data 10000, unlimited collab, and no type set (because was set manually without that requirement)
- yarn run-script updateLicense --teamspace xxx --type internal --expiryDate "2042-01-01"
- now the license when viewed with yarn run-script viewLicense --teamspace xxx

```
root@staging-66f5967b89-h6dn9:/home/node/3drepo.io/backend# yarn run-script viewLicense --teamspace xxx
yarn run v1.22.19
$ cross-env NODE_CONFIG_DIR=../config node ./src/scripts/utility/index viewLicense --teamspace xxx
{"level":"info","message":"xxx currently has the following subscription(s): {\"enterprise\":{\"collaborators\":25,\"data\":100000,\"expiryDate\":\"2022-09-30T23:59:57.858Z\"},\"internal\":{\"expiryDate\":\"2042-01-01T00:00:00.000Z\"}} ","timestamp":"2022-10-31T11:37:19.780Z"}
Done in 0.90s.
```

### Current Behaviour
- looks like if the type was originally missing then updating a license can go a bit strange.

### Expected Behaviour
- correctly formatted license environment

**Comment by carmenfan** [comment] 2022-10-31 12:22
@keifgwinn the type seems set? it's set to enterprise according to the log you dumped - I feel like I'm not understanding the situation correctly

The log shows you have an expired enterprise license with 25 collabs and 100k data, and an internal license that expires in 2042 with no quota

**Comment by keifgwinn** [comment] 2022-10-31 13:30
ok so I guess then the issue is the updateLicense script allowed me to create an invalid sub, if it doesn't have data/users. 

Would we be in a situation with one sub with users, and one sub with data?

**Comment by carmenfan** [comment] 2022-10-31 13:44
> ok so I guess then the issue is the updateLicense script allowed me to create an invalid sub, if it doesn't have data/users.

Yea the script doesn't check, and since we want it easy to just update a single term (e.g. extending a current license) within the license this is why this can happen. It's technically not invalid, it's just pointless


> Would we be in a situation with one sub with users, and one sub with data?

It's possible yes, but in practical terms it's pretty rare for a teamspace to have 2 active subs of different types

**Comment by carmenfan** [comment] 2022-11-01 10:27
Closing as working as intended

**Closed by carmenfan** 2022-11-01 10:27 UTC
Labels: bug, Triage: Awaiting
