### ISSUE TITLE
Saving camera using 'More Options' of View property does not save clipping planes 

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#4387] opened 2023-08-07 14:32 UTC
### Description
Saving a camera with clipping planes semms to not save the clipping planes if the save is done using the 'More options' way. Saving one using the tick button seems to work.

### Steps to replicate
Load a model in 3d repo
Add clipping planes
Open a ticket with a view property
Save the camera by pressing the 3 dots and then 'Save camera'
Click on Go to viewpoint.
The clipping planes are not applied

**Comment by carmenfan** [comment] 2023-08-07 15:05
duplicate of https://github.com/3drepo/3drepo.io/issues/4388

**Closed by carmenfan** 2023-08-07 15:05 UTC
Labels: bug
