### ISSUE TITLE
Updating treatment template throws an error message

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2077] opened 2020-06-11 14:19 UTC
### Description
Receive an error message when I update a treatment template. Refresh your browser page and notice that it has actually updated.

### Steps to replicate
- login to 3drepo.io
- Open your teamspace settings
- Click on the edit template icon (Pen)
- Select CSV file
- Hit Save button
- Error message a appears

### Pictures/ Gifs of the error
![Updating risk register](https://user-images.githubusercontent.com/19904513/84397689-ddd13000-abf6-11ea-8164-823cfcb516ef.gif)

**Comment by BDavydov** [comment] 2020-06-11 14:59
It appears to work fine with our CSV file, but when you save a similar Excel file as SCV it throws an error. Let me double-check it before you look at it further!

**Comment by carmenfan** [comment] 2020-08-20 16:53
I'm closing this since it's been a while and it sounds like it's working.


Reopen with a test file if we can reproduce it.

**Closed by carmenfan** 2020-08-20 16:53 UTC
