### ISSUE TITLE
Reconsider naming of .BIM file format on frontend

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2394] opened 2021-01-13 12:46 UTC
### Description

Consider describing .BIM files as BIM rather than NAVIS as these files can now come from NAVIS and REVIT plug-ins

### Goals

- Reduce confusion for users who didn't use NAVIS to upload a .BIM file

### Related Resources
![Screenshot from 2021-01-13 12-38-25](https://user-images.githubusercontent.com/1438332/104453796-db73f180-559c-11eb-82f5-bdd771b2517e.png)

**Comment by carmenfan** [comment] 2021-01-13 13:41
this is a duplicate of #2374

**Closed by carmenfan** 2021-01-13 13:41 UTC
