### ISSUE TITLE
Toy project diff not working

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2180] opened 2020-09-10 20:28 UTC
### Description
Toy project diff not working

### Steps to replicate
- Sign up for new account
- Open Toy federation
- Open Diff card and apply diff with default settings

### Pictures/ Gifs of the error
![Screenshot 2020-09-10 at 21 26 15](https://user-images.githubusercontent.com/1438332/92800269-70c36700-f3ac-11ea-8651-bb412a363369.png)

**Comment by carmenfan** [comment] 2020-09-11 10:12
This is caused by asset bundle corruption. The file is now fixed in fileshare.

**Closed by carmenfan** 2020-09-11 10:12 UTC
Labels: bug, critical, hotfix
