### ISSUE TITLE
Router history is broken when changing project in tabular view

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4940] opened 2024-04-26 15:51 UTC
### Description

The router history in tabular view appears to be broken. When changing project two entries are added to the history. If the sidebar was opened when changing project then the first entry has the sidebar opened and the second has the sidebar closed.

Sometimes changing project can cause a crash. This seems to be because it tries looking for the model ID from the initial project in the new project. It then tries to destructure this undefined model which causes a crash

- This is happening in: prod/staging/**both** 
- This requires a hotfix to production: yes/**no** 

### Steps to replicate
- Open tabular view
- View a ticket
- Use the dropdown menu to change the project
- You will now see the tabular view for the new project. The sidebar has closed
- Press back in the browser
- The project is still the same but the sidebar has opened
- (It might then even be possible to click the 'open in viewer' button which can cause an error when trying to open a model that doesn't exist)

### Current Behaviour
- Pressing back just opens the toolbar

### Expected Behaviour
- Pressing back returns you to the same state you were before changing project

## Initial state
![image](https://github.com/3drepo/3drepo.io/assets/62481250/34e8c47d-03b7-40f4-a95f-369536f17e30)
## After changing project
![image](https://github.com/3drepo/3drepo.io/assets/62481250/9c1e828f-6af0-4fd2-8b3a-2bff092dcc33)
You would expect the most recent option to be the tickets table for the previous project (i.e. Cathedral - Tickets) but there is another entry above that for the new project (Demo Project - Tickets)

## Error which sometimes occurs which causes a crash
![image](https://github.com/3drepo/3drepo.io/assets/62481250/af065ddb-6a90-4cbb-b22e-11fa8cb9e4d9)

## It is possible to open the model
![image](https://github.com/3drepo/3drepo.io/assets/62481250/6e725f37-ac26-462c-850b-e43b84a74d7a)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/1e945127-159d-4465-9c55-b793f7468974)
This can then cause another crash

**Comment by Amantini1997** [comment] 2024-05-28 11:39
Can't reproduce. Fixed in 5.10

**Closed by Amantini1997** 2024-05-28 11:39 UTC
Labels: bug, frontend
