### ISSUE TITLE
Dev 3.3.3 Bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1420] opened 2019-03-12 14:48 UTC
- [x] [Safetibase: error when next button clicked](https://github.com/3drepo/3drepo.io/issues/1420#issuecomment-472032822)
- [x] [Safetibase filter doesn't work in Firefox](https://github.com/3drepo/3drepo.io/issues/1420#issuecomment-472053129)

**Comment by paloknapo** [comment] 2019-03-12 14:50
**Safetibase: error when next button clicked**

1. open safetibase risk
2. click on the next button in card header, this error pops up

![image](https://user-images.githubusercontent.com/760452/54209690-1ce57280-44d6-11e9-9f8c-bb4b53200038.png)

**Comment by paloknapo** [comment] 2019-03-12 15:38
**Safetibase filter doesn't work in Firefox**

![01](https://user-images.githubusercontent.com/760452/54213780-e65f2600-44dc-11e9-98b6-499bf328a79d.gif)

**Comment by sanmont3drepo** [comment] 2019-03-13 10:56
The first bug was caused by a wrong data set consequence of deleting the groups manually in the db. So wont fix.

**Closed** 2019-03-20 16:50 UTC
Labels: In Staging
